Yaroslav homework 4
eugene-okulik/Yakozakov pull request #3
Opened 2024-04-03 18:51 UTC by ykz2025

Homework 4 is added for merging

2024-04-04 09:10 UTC, eugene-okulik requested changes
Во всем задании нужно работать с одной переменной: my_dict. Внутри нее нужно добавить все данные и уже с ними взаимодействовать  
будет что-то такое:
```python
my_dict = {'tuple': (1, 10, 'text', 3.14, True), 'list': [2, 111, 'Hello!', 'number', False]}
```
и так далее.

2024-04-04 09:10 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_4/homework_4.py
> +my_dict = {'tuple', 'list', 'dict', 'set'}
Это не словарь, а множество. Словарь, это когда в фигурных скобках пары ключ-значение. Здесь у тебя только значения, поэтому это множество (set)

2024-04-05 08:39 UTC, ykz2025 commented
Правки внесени
Lint пропустил код
Но Vscode ругається на єтот код, не пойму что не так..

2024-04-05 12:10 UTC, eugene-okulik requested changes

2024-04-05 12:10 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_4/homework_4.py
> +    (1, 10, 'text', 3.14, True),
Ключ и значение на разные строки обычно не разделяют.  
Лучше
```python
'tuple': (1, 10, 'text', 3.14, True),
```

2024-04-05 12:10 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_4/homework_4.py
> +dict['i am a tuple'] = 'six value'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-04-05 12:19 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_4/homework_4.py
> +dict['i am a tuple'] = 'six value'
И еще, весь словарь у тебя находится в переменной my_dict, а здесь ты обращаешься к dict, а это встроенная функция языка python.

2024-04-05 20:00 UTC, ykz2025 commented
Code is rewrite
By using chatgpt similar service as this code construction is little bit hard to read and work with it

2024-04-06 16:44 UTC, eugene-okulik requested changes

2024-04-06 16:44 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_4/homework_4.py
> +my_dict['dict'][('i am a tuple', 'six')] = 'six'
Ты добавил значение с ключом `('i am a tuple', 'six')` и это кортеж из двух элементов. Ключ должен быть таким, как в задании - кортеж с одним элементом `('i am a tuple',)`. Я в видео показывал как выглядит такой кортеж и предупреждал, что выглядит он странно, но вот так вот есть.

2024-04-06 18:07 UTC, ykz2025 commented
Так?

+вопрос по строчке 4
    'dict': {1: 1, 'one': "biger_zero", 'two': '2', 'Love': 'love', False: True},
тут 82 символа, исходя из РЕР8 макс. символов 79
как тут верно будет перенести, если отдельно значение без ключа не переносится?

2024-04-07 12:00 UTC, eugene-okulik approved these changes

2024-04-07 12:01 UTC, merged

2024-04-08 18:33 UTC, eugene-okulik commented
> Так?
> 
> +вопрос по строчке 4 'dict': {1: 1, 'one': "biger_zero", 'two': '2', 'Love': 'love', False: True}, тут 82 символа, исходя из РЕР8 макс. символов 79 как тут верно будет перенести, если отдельно значение без ключа не переносится?

Словари обычно разделяют по запятой:
```python
'dict': {
    1: 1, 
    'one': "biger_zero", 
    'two': '2', 
    'Love': 'love', 
    False: True
}
```