Yaroslav homework 5
eugene-okulik/Yakozakov pull request #4
Opened 2024-04-09 15:53 UTC by ykz2025

Homework 5 is done
Waiting for approval

2024-04-10 11:37 UTC, eugene-okulik requested changes

2024-04-10 11:37 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_5/homework_5.py
> +str3 = str('результат операции: 9')
В задании другие примеры и нужно найти подход, который будет одинаковым для всех примеров. Примеры там такие:

> результат операции: 42
> 
> результат операции: 514
> 
> результат работы программы: 9

2024-04-10 11:37 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_5/homework_5.py
> +str3 = str('результат операции: 9')
Заморочка в том, чтобы найти в этой строке число, каким бы оно там ни было. Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.

2024-04-10 12:26 UTC, ykz2025 commented on homework/yaroslav_kozakov/Homework_5/homework_5.py
> +str3 = str('результат операции: 9')
Ладно решение неверно, видимо нужно через сплит отделить сначала цифри и отобразить их через int

**_В задании другие примеры и нужно найти подход, который будет одинаковым для всех примеров._** 
Но я не понимаю, как отобразить в коде условие задачи
я так понимаю, я неверно єто указал исходя из твоего комментария

2024-04-10 16:35 UTC, eugene-okulik requested changes

2024-04-10 16:35 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_5/homework_5.py
> +str3 = str('результат операции: 9')
Сейчас у тебя в коде так:
```python
str1 = 'результат операции: 42'
str2 = 'результат операции: 514'
str3 = 'результат операции: 9'
```
`str` там были лишними и я их убрал  
А если использовать примеры из задания, будет так
```python
str1 = 'результат операции: 42'
str2 = 'результат операции: 514'
str3 = 'результат работы программы: 9'
```
Ну и сразу становится понятно, что твой код, который ищет число в этой строке, к тексту из str3 не подходит. Но нужно написать такой код, который сможет найти число и если ему дать `str1` и если ему дать `str2` и если ему дать `str3`.

2024-04-10 16:37 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_5/homework_5.py
> +str3 = str('результат операции: 9')
> Ладно решение неверно, видимо нужно через сплит отделить сначала цифри и отобразить их через int

Через сплит можно, но в задании сказано, что нужно решить через срезы и index. Вот когда не будет указан конкретный способ как должно быть решено, тогда можно и сплит.

2024-04-10 16:39 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_5/homework_5.py
> +str3_colon_index = str3.index(':')
Вот да, это решение - правильное. Похоже, ты его сделал пока я последний коммент писал - я как-то не понял когда появилось это решение.

2024-04-10 16:40 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_5/homework_5.py
> +number_result = number_str1_new + number_str2_new + number_str3_new
Единственное, в задании не было указания распечатать сумму всех чисел. В результате, по сути, нужно распечатать только number_str1_new, number_str2_new и number_str3_new

2024-04-10 16:42 UTC, eugene-okulik commented on homework/yaroslav_kozakov/Homework_5/homework_5.py
> +number_result = number_str1_new + number_str2_new + number_str3_new
но это ерунда, можно не исправлять.

2024-04-10 17:48 UTC, ykz2025 commented
Ok
As I understood my code execution is accepted
waiting for merge and the next lesson
Thank you

2024-04-11 10:26 UTC, eugene-okulik approved these changes

2024-04-11 10:26 UTC, merged